on:
  workflow_dispatch:
    inputs:
      title:
        description: "title"
        required: true
        type: string
      tldr:
        description: "tldr"
        required: false
        type: string
      type:
        description: "type"
        required: true
        default: "link"
        type: choice
        options:
          - link
      tags:
        description: "tags"
        required: true
        type: string
      url:
        description: "url"
        required: true
        type: string
jobs:
  create-post:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: set file name
        id: set-file-name
        run: |
          DATE=$(date + "%Y%m%d")
          FILE_NAME=$(echo "${DATE}_${{ github.event.inputs.title }}" | tr ' ' '-')
          PUB_DATE=$(date +"%b %-d %Y")
          echo "file_name=$FILE_NAME" >> $GITHUB_OUTPUT
          echo "pub_date=$PUB_DATE" >> $GITHUB_OUTPUT
      - name: convert tags to array
        id: convert-tags
        run: |
          IFS=',' read -ra TAGS_ARRAY <<< "${{ github.event.inputs.tags }}"
          TAGS_STRING=$(IFS=,; printf "'%s'," "${TAGS_ARRAY[@]}" | sed 's/,$//')
          echo $TAGS_STRING
          echo "tags_string=$TAGS_STRING" >> $GITHUB_OUTPUT
      - name: create post markdown file
        run: |
          cd src/content/blog
          echo "---" > ${{ steps.set-file-name.outputs.file_name }}.md
          echo "type: '${{ github.event.inputs.type }}'" >> ${{ steps.set-file-name.outputs.file_name }}.md
          echo "title: '${{ github.event.inputs.title }}'" >> ${{ steps.set-file-name.outputs.file_name }}.md
          echo "tldr: '${{ github.event.inputs.tldr }}'" >> ${{ steps.set-file-name.outputs.file_name }}.md
          echo "pubDate: '${{ steps.set-file-name.outputs.pub_date }}'" >> ${{ steps.set-file-name.outputs.file_name }}.md
          echo "tags: [${{ steps.convert-tags.outputs.tags_string }}]" >> ${{ steps.set-file-name.outputs.file_name }}.md
          echo "url: '${{ github.event.inputs.url }}'" >> ${{ steps.set-file-name.outputs.file_name }}.md
          echo "---" >> ${{ steps.set-file-name.outputs.file_name }}.md
          cat ${{ steps.set-file-name.outputs.file_name }}.md
      - name: commit and push
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add src/content/blog/${{ steps.set-file-name.outputs.file_name }}.md
          git commit -m "Created ${{ steps.set-file-name.outputs.file_name }}.md"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
